version: '3.8'
services:
  app:
    image: "node:latest" 
    working_dir: /app
    command: "npm start"
    container_name: app
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    restart: always
  mongoexpress:
        image: mongo-express
        ports:
            - "8081:8081"
        links:
            - mongo
        environment: 
            - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
  